spring:
  main:
    allow-bean-definition-overriding: true
  application:
      name: proyecto
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: true
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 2000
    password: example
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=proyecto
    initialization-mode: never